JC = javac
JFLAGS = -g


default: Constraint.class Feedback.class Logger.class Main.class Matcher.class PaymentSystem.class Preference.class Request.class Requester.class Responder.class Scheduler.class Tracker.class 


Constraint.class: Constraint.java
        $(JCC) $(JFLAGS) Constraint.java

Feedback.class: Feedback.java
        $(JCC) $(JFLAGS) Feedback.java

Logger.class: Logger.java
        $(JCC) $(JFLAGS) Logger.java

Main.class: Main.java
        $(JCC) $(JFLAGS) Main.java

Matcher.class: Matcher.java
        $(JCC) $(JFLAGS) Matcher.java

PaymentSystem.class: PaymentSystem.java
        $(JCC) $(JFLAGS) PaymentSystem.java

Preference.class: Preference.java
        $(JCC) $(JFLAGS) Preference.java

Request.class: Request.java
        $(JCC) $(JFLAGS) Request.java

Requester.class: Requester.java
        $(JCC) $(JFLAGS) Requester.java       

Responder.class: Responder.java
        $(JCC) $(JFLAGS) Responder.java

Response.class: Response.java
        $(JCC) $(JFLAGS) Response.java  

Scheduler.class: Scheduler.java
        $(JCC) $(JFLAGS) Scheduler.java

Tracker.class: Tracker.java
        $(JCC) $(JFLAGS) Tracker.java  

clean:
	$(RM) *.class
